modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/FireMuffin303/Muffins-ThaiDelight/issues"
license = "MIT License"

[[mods]]
modId = "muffins_thaidelight"
version = "${version}"
displayName = "Muffin's Thai's Delight"
authors = "FireMuffin303"
credits = "lllLucaslll - Concept Artist"
description = '''
Cooking expansion focus on Thai's Food!
'''
logoFile = "assets/muffins_thaidelight/logo.png"

[[dependencies.muffins_thaidelight]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_thaidelight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.muffins_thaidelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.20.1-1.2.3,)"
ordering = "NONE"
side = "BOTH"
