pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = "architectury"
            url = "https://maven.architectury.dev/"
        }
        maven {
            name = "forge"
            url = "https://files.minecraftforge.net/maven/"
        }
        gradlePluginPortal()
    }
}

rootProject.name = "muffins_thaidelight"

include(
        "common",
        "fabric",
        "neoforge"
)